/*
 * themes — saved palettes, read off disk.
 *
 * A theme is two ramps of primitives and nothing else. It does not touch the
 * semantic layer: `--muted` points at `--muza-neutrals-900` in light and dark
 * by a decision that belongs in `app.css`, and a theme that could re-point it
 * would be a second place where that decision lives.
 *
 * Files come from `app/themes/*.json` through `import.meta.glob`, the same
 * mechanism the component docs use: inlined at build time, so a saved theme
 * ships with the page and nothing is fetched at runtime. `muza-default.json`
 * is generated from `app.css` and is the way back from any experiment.
 *
 * Applying a theme writes inline custom properties onto `<html>`, which is the
 * last word in the cascade — the whole page changes, not a preview panel.
 * Clearing them hands the page back to the stylesheet.
 */

export interface ThemeRamp {
  prefix: string
  /** Step number → colour, exactly as it should be written in CSS. */
  steps: Record<string, string>
  /** The five numbers, when the ramp was generated rather than listed. */
  curve?: { hue: number; chroma: number; top: number; bottom: number; contrast: number }
  /** Steps deliberately held off the curve. */
  pinned?: string[]
}

export interface Theme {
  name: string
  label?: string
  note?: string
  created?: string
  ramps: Record<string, ThemeRamp>
}

const FILES = import.meta.glob("/app/themes/*.json", { eager: true }) as
  Record<string, { default: Theme }>

/** Every saved theme, `muza-default` first and the rest alphabetical. */
export const THEMES: Theme[] = Object.entries(FILES)
  .map(([, mod]) => mod.default)
  .sort((a, b) =>
    a.name === "muza-default" ? -1 : b.name === "muza-default" ? 1
      : a.name.localeCompare(b.name))

export const DEFAULT_THEME = THEMES.find(t => t.name === "muza-default")

/** Write a theme's primitives onto the document. */
export function applyTheme(theme: Theme) {
  const el = document.documentElement
  for (const ramp of Object.values(theme.ramps)) {
    for (const [step, value] of Object.entries(ramp.steps)) {
      el.style.setProperty(`--${ramp.prefix}${step}`, value)
    }
  }
}

/** Hand the page back to `app.css`. */
export function clearTheme(theme: Theme = DEFAULT_THEME as Theme) {
  const el = document.documentElement
  for (const ramp of Object.values(theme?.ramps ?? {})) {
    for (const step of Object.keys(ramp.steps)) {
      el.style.removeProperty(`--${ramp.prefix}${step}`)
    }
  }
}

/** The theme as a stylesheet block — what gets written next to the JSON. */
export function themeCss(theme: Theme): string {
  const lines: string[] = [
    `/* ${theme.label ?? theme.name} — generated by the ramp controller.`,
    ` * Primitives only: the semantic layer in app.css is untouched. */`,
    `:root {`,
  ]
  for (const [id, ramp] of Object.entries(theme.ramps)) {
    lines.push(`  /* ${id} */`)
    for (const [step, value] of Object.entries(ramp.steps)) {
      lines.push(`  --${ramp.prefix}${step}: ${value};`)
    }
  }
  lines.push(`}`, ``)
  return lines.join("\n")
}

/** POST to the dev server's writer. Returns the files it wrote. */
export async function saveTheme(theme: Theme): Promise<string[]> {
  const res = await fetch("/__theme", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ name: theme.name, json: theme, css: themeCss(theme) }),
  })
  const data = await res.json() as { ok: boolean; files?: string[]; error?: string }
  if (!data.ok) throw new Error(data.error ?? "save failed")
  return data.files ?? []
}
